baseURL: '/'
languageCode: 'fr-FR'
title: My New Hugo Site
defaultContentLanguage: fr
languages:
  fr:
    code: fr
    languageName: 'Français'
    weight: 1

ignoreFiles:
  - \.jsconfig.json$

taxonomies:
  category: categories